package domestia_player_choice;

import com.mojang.serialization.MapCodec;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.HorizontalDirectionalBlock;
import net.minecraft.world.level.block.Mirror;
import net.minecraft.world.level.block.Rotation;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.DoubleBlockHalf;
import net.minecraft.world.level.block.state.properties.EnumProperty;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.shapes.CollisionContext;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

public class PlayerChoiceBoardBlock extends HorizontalDirectionalBlock {
	public static final MapCodec<PlayerChoiceBoardBlock> CODEC = simpleCodec(properties -> new PlayerChoiceBoardBlock(properties, false));
	public static final EnumProperty<Direction> FACING = BlockStateProperties.HORIZONTAL_FACING;
	public static final EnumProperty<DoubleBlockHalf> HALF = BlockStateProperties.DOUBLE_BLOCK_HALF;

	/*
	 * Shapes are intentionally split by block half and mounting mode.
	 * The board models are not full cubes, so a single old rectangle makes ray hits
	 * feel wrong. These box lists mirror the current Blockbench elements as closely
	 * as vanilla VoxelShape allows. The tilted standing parts are represented by
	 * their rotated axis-aligned bounds, because VoxelShape cannot be an angled box.
	 * Coordinates below are in Blockbench model units, based on the north-facing
	 * model orientation. Other facings are generated by rotating around the block
	 * center, the same way blockstate model rotations work.
	 */
	private static final double[][] STANDING_LOWER_BOXES_NORTH = new double[][] {
			{1.0D, 0.0D, 6.0D, 3.0D, 2.0D, 16.0D},
			{13.0D, 0.0D, 6.0D, 15.0D, 2.0D, 16.0D},
			{12.0D, 0.0D, 5.0D, 14.0D, 15.856D, 15.732D},
			{2.0D, 0.0D, 5.0D, 4.0D, 15.856D, 15.732D},
			{4.0D, 8.794D, 11.366D, 12.0D, 15.356D, 15.732D},
			{3.0D, 0.0D, 13.0D, 13.0D, 2.0D, 15.0D},
			{4.0D, 14.0D, 15.0D, 12.0D, 16.0D, 16.0D},
			{3.0D, 14.0D, 14.0D, 4.0D, 16.0D, 16.0D},
			{12.0D, 14.0D, 14.0D, 13.0D, 16.0D, 16.0D}
	};

	private static final double[][] WALL_LOWER_BOXES_NORTH = new double[][] {
			{4.0D, 3.0D, 15.0D, 12.0D, 16.0D, 16.0D},
			{2.0D, 1.0D, 14.0D, 4.0D, 16.0D, 16.0D},
			{12.0D, 1.0D, 14.0D, 14.0D, 16.0D, 16.0D}
	};

	private static final double[][] UPPER_BOXES_NORTH = new double[][] {
			{1.0D, 0.0D, 14.0D, 15.0D, 14.0D, 16.0D},
			{14.0D, 2.0D, 13.0D, 16.0D, 12.0D, 15.0D}
	};

	private static final VoxelShape STANDING_LOWER_NORTH = shapeForFacing(STANDING_LOWER_BOXES_NORTH, Direction.NORTH);
	private static final VoxelShape STANDING_LOWER_EAST = shapeForFacing(STANDING_LOWER_BOXES_NORTH, Direction.EAST);
	private static final VoxelShape STANDING_LOWER_SOUTH = shapeForFacing(STANDING_LOWER_BOXES_NORTH, Direction.SOUTH);
	private static final VoxelShape STANDING_LOWER_WEST = shapeForFacing(STANDING_LOWER_BOXES_NORTH, Direction.WEST);

	private static final VoxelShape WALL_LOWER_NORTH = shapeForFacing(WALL_LOWER_BOXES_NORTH, Direction.NORTH);
	private static final VoxelShape WALL_LOWER_EAST = shapeForFacing(WALL_LOWER_BOXES_NORTH, Direction.EAST);
	private static final VoxelShape WALL_LOWER_SOUTH = shapeForFacing(WALL_LOWER_BOXES_NORTH, Direction.SOUTH);
	private static final VoxelShape WALL_LOWER_WEST = shapeForFacing(WALL_LOWER_BOXES_NORTH, Direction.WEST);

	private static final VoxelShape UPPER_NORTH = shapeForFacing(UPPER_BOXES_NORTH, Direction.NORTH);
	private static final VoxelShape UPPER_EAST = shapeForFacing(UPPER_BOXES_NORTH, Direction.EAST);
	private static final VoxelShape UPPER_SOUTH = shapeForFacing(UPPER_BOXES_NORTH, Direction.SOUTH);
	private static final VoxelShape UPPER_WEST = shapeForFacing(UPPER_BOXES_NORTH, Direction.WEST);

	private final boolean wallMounted;

	public PlayerChoiceBoardBlock(BlockBehaviour.Properties properties, boolean wallMounted) {
		super(properties);
		this.wallMounted = wallMounted;
		this.registerDefaultState(this.stateDefinition.any()
				.setValue(FACING, Direction.NORTH)
				.setValue(HALF, DoubleBlockHalf.LOWER));
	}

	@Override
	protected MapCodec<? extends HorizontalDirectionalBlock> codec() {
		return CODEC;
	}

	public boolean isWallMounted() {
		return this.wallMounted;
	}

	@Override
	protected VoxelShape getShape(BlockState state, BlockGetter level, BlockPos pos, CollisionContext context) {
		return getShapeForState(state);
	}

	@Override
	protected VoxelShape getCollisionShape(BlockState state, BlockGetter level, BlockPos pos, CollisionContext context) {
		return getShapeForState(state);
	}

	private static VoxelShape getShapeForState(BlockState state) {
		Direction facing = state.getValue(FACING);
		boolean upper = state.getValue(HALF) == DoubleBlockHalf.UPPER;
		Block block = state.getBlock();
		boolean wallMounted = block instanceof PlayerChoiceBoardBlock boardBlock && boardBlock.isWallMounted();

		if (upper) {
			return switch (facing) {
				case EAST -> UPPER_EAST;
				case SOUTH -> UPPER_SOUTH;
				case WEST -> UPPER_WEST;
				default -> UPPER_NORTH;
			};
		}

		if (wallMounted) {
			return switch (facing) {
				case EAST -> WALL_LOWER_EAST;
				case SOUTH -> WALL_LOWER_SOUTH;
				case WEST -> WALL_LOWER_WEST;
				default -> WALL_LOWER_NORTH;
			};
		}

		return switch (facing) {
			case EAST -> STANDING_LOWER_EAST;
			case SOUTH -> STANDING_LOWER_SOUTH;
			case WEST -> STANDING_LOWER_WEST;
			default -> STANDING_LOWER_NORTH;
		};
	}

	private static VoxelShape shapeForFacing(double[][] boxes, Direction facing) {
		VoxelShape shape = Shapes.empty();

		for (double[] box : boxes) {
			shape = Shapes.or(shape, boxForFacing(box, facing));
		}

		return shape.optimize();
	}

	private static VoxelShape boxForFacing(double[] box, Direction facing) {
		double minX = box[0];
		double minY = box[1];
		double minZ = box[2];
		double maxX = box[3];
		double maxY = box[4];
		double maxZ = box[5];

		return switch (facing) {
			case EAST -> Block.box(16.0D - maxZ, minY, minX, 16.0D - minZ, maxY, maxX);
			case SOUTH -> Block.box(16.0D - maxX, minY, 16.0D - maxZ, 16.0D - minX, maxY, 16.0D - minZ);
			case WEST -> Block.box(minZ, minY, 16.0D - maxX, maxZ, maxY, 16.0D - minX);
			default -> Block.box(minX, minY, minZ, maxX, maxY, maxZ);
		};
	}

	@Override
	protected InteractionResult useItemOn(
			ItemStack stack,
			BlockState state,
			Level level,
			BlockPos pos,
			Player player,
			InteractionHand hand,
			BlockHitResult hitResult
	) {
		return this.handleBoardInteraction(state, level, player, hitResult);
	}

	@Override
	protected InteractionResult useWithoutItem(
			BlockState state,
			Level level,
			BlockPos pos,
			Player player,
			BlockHitResult hitResult
	) {
		return this.handleBoardInteraction(state, level, player, hitResult);
	}

	private InteractionResult handleBoardInteraction(BlockState state, Level level, Player player, BlockHitResult hitResult) {
		if (hitResult.getDirection() != state.getValue(FACING)) {
			return InteractionResult.PASS;
		}

		if (level.isClientSide()) {
			PlayerChoiceScreenOpener.open();
		}

		return InteractionResult.SUCCESS;
	}

	@Override
	public BlockState playerWillDestroy(Level level, BlockPos pos, BlockState state, Player player) {
		if (!level.isClientSide()) {
			BlockPos otherPos = state.getValue(HALF) == DoubleBlockHalf.LOWER ? pos.above() : pos.below();
			BlockState otherState = level.getBlockState(otherPos);

			if (otherState.getBlock() == this && otherState.getValue(HALF) != state.getValue(HALF)) {
				level.setBlock(otherPos, Blocks.AIR.defaultBlockState(), 35);
			}
		}

		return super.playerWillDestroy(level, pos, state, player);
	}

	@Override
	protected BlockState rotate(BlockState state, Rotation rotation) {
		return state.setValue(FACING, rotation.rotate(state.getValue(FACING)));
	}

	@Override
	protected BlockState mirror(BlockState state, Mirror mirror) {
		return state.rotate(mirror.getRotation(state.getValue(FACING)));
	}

	@Override
	protected void createBlockStateDefinition(StateDefinition.Builder<Block, BlockState> builder) {
		builder.add(FACING, HALF);
	}
}
